#!/bin/bash

echo "This will install the pr2-kinect2-packages package on your computer."
echo "This package is only intended for use with an Intel NUC which will be connected to a Kinect 2"
read -r -p "If run on a computer other than a NUC, it may irrevocably damage your OS installation. Are you sure you want to continue? [y/N] " input
input = ${input,,}

if [[ $input =~ ^(yes|y)$ ]];
then
  echo "Continuing with installation!"
  exit 0
else
  echo "Aborting installation!"
  exit 1
fi
